### ISSUE TITLE
Make list of data sources to process to the dashboard

### ISSUE THREAD

**Issue by beefoo** [MonumentLab/national-monument-audit#11]
All major national sources, best one from each state (if applicable), notable local/city/county data sources:

https://docs.google.com/document/d/1368v2ZyKuMocy1YpLZtkORGCXXB-ZqncAG4EGMZ8T00/edit?usp=sharing

**Comment by mokech** [comment]
Update 1/25: Results from initial scan of sources when I sorted by data assessment. Will continue more methodologically next. See "data for brian" tab. https://docs.google.com/spreadsheets/d/16YGiLFMHDBukEA6Rp6v9J6Udnt0uEU5ncI70pIOykqI/edit#gid=1966487529 @beefoo
