### ISSUE TITLE
Process NPS data

### ISSUE THREAD

**Issue by beefoo** [MonumentLab/national-monument-audit#2]
National Register Of Historic Places: [https://public-nps.opendata.arcgis.com/datasets/national-register-of-historic-places-points/data](https://public-nps.opendata.arcgis.com/datasets/national-register-of-historic-places-points/data)
    NPS - Points of Interest (POIs): [https://public-nps.opendata.arcgis.com/datasets/nps-points-of-interest-pois-web-mercator/data](https://public-nps.opendata.arcgis.com/datasets/nps-points-of-interest-pois-web-mercator/data)

**Comment by librlaurie** [comment]
I wrote to a contact at NPS this morning to ask about how much data is in CRIS that is not here, and also if she can point to similar resources.

**Comment by beefoo** [comment]
Processed National Register and POI data; not a whole lot (a couple thousand entries), but something
