### ISSUE TITLE
Process Smithsonian SOS data

### ISSUE THREAD

**Issue by beefoo** [MonumentLab/national-monument-audit#6]
Data is in a bunch of different places. Not sure which is easiest to get:

This one truncates to 500 page search result, so will need to facet by state:
https://collections.si.edu/search/results.htm?view=&dsort=&date.slider=&fq=object_type%3A%22Outdoor+sculpture%22&fq=data_source%3A%22Art+Inventories+Catalog%2C+Smithsonian+American+Art+Museum%22&q=

This one also gives state by state results:
https://sirismm.si.edu/siris/ariquickstart.htm

**Comment by librlaurie** [comment]
Paul and I are being connected with a lawyer at the Berkman Center who will talk to us about fair use claims for this. I'll keep you informed. We also have flagged it with Mellon, and have another call with Smithsonian folks in early February. So, keeping fingers crossed.
